"""
hull_mdo_surrogate.py
=====================
Surrogate-based hull MDO pipeline.

Workflow
--------
1. Load the full dataset from hull_dataset.csv  (generated by generate_dataset.py)
2. Split 50/50 into train and test sets
3. Fit RBF surrogates on the TRAIN half:   h → R_surr,  h → V_surr
4. Validate on the TEST half:
     compare surrogate predictions vs truth-model values
     → this confirms the surrogate generalises before we trust the optimizer
5. Optimize with CSDL + SQP:
     minimise R_surr(h)  subject to  |V_surr(h) - V_ref| ≤ γ·V_ref
6. Evaluate the optimal h on the TRUTH model and report results
7. Plot initial vs optimal hull geometry

Why RBF instead of a polynomial?
---------------------------------
The original quadratic polynomial surrogate used features [1, z, z²] with
no cross-terms. Resistance is nonlinear and depends on interactions between
parameters (e.g. bow sharpness × fullness). A radial basis function (RBF)
with a thin-plate-spline kernel  φ(r) = r² log(r)  captures these
interactions naturally and is smooth enough for gradient-based optimization.

Usage
-----
    # First generate data (only needs to be done once):
    python generate_dataset.py

    # Then run the surrogate pipeline:
    python hull_mdo_surrogate.py
    python hull_mdo_surrogate.py --csv hull_dataset.csv --gamma 0.03
"""

import argparse
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.lines import Line2D
from scipy.interpolate import splprep, splev, CubicSpline

import csdl_alpha as csdl
import modopt as opt

from True_model_test import (
    CONST, compute_R_and_V,
    build_control_points, hull_curves, _sort_interp,
)
from Gen_data_test import load_csv


# ============================================================
# 1)  RBF SURROGATE  (thin-plate-spline kernel, direct h → R / V)
# ============================================================

def _tps_kernel(r: np.ndarray) -> np.ndarray:
    """Thin-plate-spline kernel  φ(r) = r² log(r),  with φ(0) = 0."""
    r = np.maximum(r, 1e-300)
    return r**2 * np.log(r)


def fit_rbf(
    X_train: np.ndarray,
    y_train: np.ndarray,
    lam: float = 1e-4,
) -> dict:
    """
    Fit an RBF surrogate:  ŷ(x) = Σ w_i φ(‖x-x_i‖) + p(x)
    where p(x) = c₀ + c₁·x₁ + … is a linear polynomial trend.

    Parameters
    ----------
    X_train : (n, d)  training inputs
    y_train : (n,)    training targets
    lam     : float   Tikhonov regularisation (prevents overfitting to noise)

    Returns
    -------
    model dict containing weights, polynomial coefficients, and
    normalisation statistics needed for prediction.
    """
    n, d = X_train.shape
    y_train = y_train.reshape(-1, 1)

    # Standardise inputs → better-conditioned distance matrix
    mu_x  = X_train.mean(0)
    sig_x = X_train.std(0);  sig_x[sig_x < 1e-12] = 1.0
    Z     = (X_train - mu_x) / sig_x                    # (n, d)

    # Standardise output
    mu_y  = float(y_train.mean())
    sig_y = float(y_train.std());  sig_y = max(sig_y, 1e-12)
    Ys    = (y_train - mu_y) / sig_y                     # (n, 1)

    # Pairwise distances between training centres
    diff  = Z[:, None, :] - Z[None, :, :]               # (n, n, d)
    r_mat = np.sqrt(np.sum(diff**2, axis=-1))            # (n, n)
    Phi   = _tps_kernel(r_mat)                           # (n, n)

    # Polynomial trend basis  P = [1, z₁, …, z_d]  shape (n, d+1)
    P = np.hstack([np.ones((n, 1)), Z])                  # (n, d+1)

    # Solve the block-symmetric RBF system:
    #   | Phi + λI   P  | | w |   | Ys |
    #   |  Pᵀ        0  | | c | = |  0 |
    n_poly = d + 1
    A = np.zeros((n + n_poly, n + n_poly))
    A[:n,  :n]  = Phi + lam * np.eye(n)
    A[:n,  n:]  = P
    A[n:,  :n]  = P.T
    # bottom-right block stays zero (unbiased polynomial conditions)

    rhs       = np.zeros((n + n_poly, 1))
    rhs[:n]   = Ys

    sol = np.linalg.solve(A, rhs)                        # (n + d+1, 1)
    w   = sol[:n].flatten()                              # RBF weights
    c   = sol[n:].flatten()                              # polynomial coeffs

    return dict(
        Z_train=Z, w=w, c=c,
        mu_x=mu_x, sig_x=sig_x,
        mu_y=mu_y, sig_y=sig_y,
        n=n, d=d,
    )


def predict_rbf_numpy(x: np.ndarray, model: dict) -> np.ndarray:
    """
    Evaluate the RBF surrogate at one or many points (pure numpy).

    Parameters
    ----------
    x     : (d,) or (m, d)
    model : dict returned by fit_rbf

    Returns
    -------
    y : (m,) predicted values  [or scalar if single input]
    """
    single = (x.ndim == 1)
    if single:
        x = x.reshape(1, -1)

    z    = (x - model["mu_x"]) / model["sig_x"]          # (m, d)
    diff = z[:, None, :] - model["Z_train"][None, :, :]  # (m, n, d)
    r    = np.sqrt(np.sum(diff**2, axis=-1))              # (m, n)
    phi  = _tps_kernel(r)                                 # (m, n)
    P    = np.hstack([np.ones((len(z), 1)), z])           # (m, d+1)

    ys   = phi @ model["w"] + P @ model["c"]             # (m,)
    y    = ys * model["sig_y"] + model["mu_y"]

    return float(y[0]) if single else y


def predict_rbf_csdl(h_var: csdl.Variable, model: dict) -> csdl.Variable:
    """
    Evaluate the RBF surrogate inside a CSDL computation graph.
    Enables exact automatic differentiation for the optimizer.

    φ(r) = r² log(r) = ½ · r² · log(r²)   (avoids sqrt, numerically stable)

    Parameters
    ----------
    h_var : csdl.Variable  shape (29,)
    model : dict returned by fit_rbf

    Returns
    -------
    scalar csdl.Variable  (predicted R or V)
    """
    Z_train = model["Z_train"]   # (n, d)  numpy constant
    w       = model["w"]         # (n,)    numpy constant
    c       = model["c"]         # (d+1,)  numpy constant
    mu_x    = model["mu_x"]
    sig_x   = model["sig_x"]
    mu_y    = float(model["mu_y"])
    sig_y   = float(model["sig_y"])
    n       = model["n"]

    # Standardise input
    z = (h_var - mu_x) / sig_x                           # (d,)

    # Compute φ(‖z - zᵢ‖) for each training centre i
    # φ(r) = ½ r² log(r²),  so we work with r² = ‖diff‖² to avoid sqrt
    phi_list = []
    for i in range(n):
        diff_i  = z - Z_train[i]                          # (d,)
        r2      = csdl.sum(diff_i * diff_i)               # scalar
        # Clamp to avoid log(0)
        r2_safe = csdl.maximum(r2, csdl.Variable(value=np.array([1e-300])))
        phi_i   = 0.5 * r2_safe * csdl.log(r2_safe)      # ½ r² log(r²)
        phi_list.append(csdl.reshape(phi_i, (1,)))

    phi_vec = csdl.concatenate(phi_list)                  # (n,)

    # Polynomial trend [1, z₁, …, z_d]
    ones  = csdl.Variable(value=np.ones(1))
    p_vec = csdl.concatenate([ones, z])                   # (d+1,)

    ys = csdl.sum(phi_vec * w) + csdl.sum(p_vec * c)     # scalar
    return ys * sig_y + mu_y


# ============================================================
# 2)  TRAIN / TEST SPLIT & VALIDATION
# ============================================================

def train_test_split(
    H: np.ndarray,
    R: np.ndarray,
    V: np.ndarray,
    test_fraction: float = 0.5,
) -> tuple:
    """
    Split dataset chronologically (first half train, second half test).
    Chronological split is preferred over random here because the Halton
    sequence already provides uniform coverage — random shuffling would
    give the same spatial coverage to both halves anyway, but chronological
    is more transparent and reproducible.

    Returns
    -------
    H_train, R_train, V_train, H_test, R_test, V_test
    """
    n      = len(R)
    n_test = int(n * test_fraction)
    split  = n - n_test            # train: [0, split),  test: [split, n)

    return (H[:split], R[:split], V[:split],
            H[split:], R[split:], V[split:])


def validate_surrogate(
    H_test: np.ndarray,
    R_test: np.ndarray,
    V_test: np.ndarray,
    R_surr: dict,
    V_surr: dict,
) -> dict:
    """
    Compare surrogate predictions against truth-model values on the test set.

    This is exactly what your partner described:
      - surrogate was trained on H_train
      - we now predict R and V for H_test
      - compare to the truth-model values R_test, V_test that were
        computed by generate_dataset.py and saved in the CSV
      → quantifies how well the surrogate generalises to unseen designs

    Returns a dict of metrics.
    """
    R_pred = predict_rbf_numpy(H_test, R_surr)
    V_pred = predict_rbf_numpy(H_test, V_surr)

    def rmse(a, b): return float(np.sqrt(np.mean((a - b)**2)))
    def mae(a,  b): return float(np.mean(np.abs(a - b)))
    def r2(a,   b):
        ss_res = np.sum((a - b)**2)
        ss_tot = np.sum((a - a.mean())**2)
        return float(1.0 - ss_res / ss_tot) if ss_tot > 0 else 0.0

    metrics = dict(
        R_rmse = rmse(R_test, R_pred),
        R_mae  = mae( R_test, R_pred),
        R_r2   = r2(  R_test, R_pred),
        V_rmse = rmse(V_test, V_pred),
        V_mae  = mae( V_test, V_pred),
        V_r2   = r2(  V_test, V_pred),
        R_pred = R_pred,
        V_pred = V_pred,
    )
    return metrics


def print_validation(metrics: dict, n_train: int, n_test: int) -> None:
    print(f"\n{'─'*55}")
    print(f"  Surrogate validation  "
          f"(train={n_train}, test={n_test})")
    print(f"{'─'*55}")
    print(f"  Resistance R:")
    print(f"    RMSE = {metrics['R_rmse']:.4f} N")
    print(f"    MAE  = {metrics['R_mae']:.4f} N")
    print(f"    R²   = {metrics['R_r2']:.4f}    (1.0 = perfect)")
    print(f"  Volume V:")
    print(f"    RMSE = {metrics['V_rmse']:.5f} m³")
    print(f"    MAE  = {metrics['V_mae']:.5f} m³")
    print(f"    R²   = {metrics['V_r2']:.4f}")
    r2_ok = metrics['R_r2'] > 0.95 and metrics['V_r2'] > 0.95
    verdict = "✓ Surrogate is accurate — safe to optimise." if r2_ok else \
              "⚠ R² < 0.95 — consider more training data or check physics."
    print(f"\n  {verdict}")
    print(f"{'─'*55}")


# ============================================================
# 3)  CSDL OPTIMIZATION PROBLEM
# ============================================================

def build_problem(
    R_surr: dict,
    V_surr: dict,
    V_ref: float,
    gamma: float = 0.02,
    h0: np.ndarray = None,
) -> tuple:
    """
    Build the CSDL optimization problem.

    Objective  : minimise R_surr(h)
    Constraint : (1-γ)·V_ref ≤ V_surr(h) ≤ (1+γ)·V_ref
    Design var : h ∈ [0, 1]^29

    The volume band constraint preserves displacement —
    so we reduce resistance without shrinking the hull.
    """
    if h0 is None:
        h0 = 0.5 * np.ones(29)

    rec = csdl.Recorder(inline=True)
    rec.start()

    h = csdl.Variable(value=h0.copy(), name="h")
    h.set_as_design_variable(lower=np.zeros(29), upper=np.ones(29))

    # Direct surrogates — single-stage, no CP intermediate
    R_hat = predict_rbf_csdl(h, R_surr)
    V_hat = predict_rbf_csdl(h, V_surr)

    R_hat.set_as_objective()
    ((1.0 - gamma) * V_ref - V_hat).set_as_constraint(upper=0.0)  # lower bound
    (V_hat - (1.0 + gamma) * V_ref).set_as_constraint(upper=0.0)  # upper bound

    rec.stop()
    sim  = csdl.experimental.PySimulator(rec)
    prob = opt.CSDLAlphaProblem(problem_name="HullOpt", simulator=sim)
    prob.x0 = h0.copy()
    return prob, sim


# ============================================================
# 4)  VISUALIZATION
# ============================================================

def cross_section_bezier(cv: dict) -> tuple:
    curve = cv["front_xsec"]
    return curve[:, 1], curve[:, 2]


def cross_section_ellipse(x_station: float, cv: dict, n: int = 200) -> tuple:
    half_beam = float(_sort_interp(cv["deck_edge"], np.array([x_station]), col=1))
    z_keel    = float(_sort_interp(cv["keel_line"], np.array([x_station]), col=2))
    draft     = max(-z_keel, 0.0)
    y = np.linspace(-half_beam, half_beam, n)
    z = (-draft * np.sqrt(np.maximum(1.0 - (y / half_beam)**2, 0.0))
         if half_beam > 1e-9 and draft > 1e-9
         else np.zeros_like(y))
    return y, z


def plot_validation(
    R_test: np.ndarray,
    V_test: np.ndarray,
    metrics: dict,
) -> None:
    """Parity plots: surrogate predictions vs truth-model values on test set."""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 5))
    fig.suptitle("Surrogate Validation — Test Set  "
                 "(surrogate predictions vs truth model)",
                 fontsize=13, fontweight="bold")

    for ax, truth, pred, label, unit in [
        (ax1, R_test, metrics["R_pred"], "Resistance R", "N"),
        (ax2, V_test, metrics["V_pred"], "Volume V",     "m³"),
    ]:
        r2_val = metrics[f"{'R' if label[0]=='R' else 'V'}_r2"]
        rmse   = metrics[f"{'R' if label[0]=='R' else 'V'}_rmse"]
        ax.scatter(truth, pred, s=18, alpha=0.55, color="steelblue",
                   edgecolors="none")
        lo = min(truth.min(), pred.min())
        hi = max(truth.max(), pred.max())
        ax.plot([lo, hi], [lo, hi], "r--", lw=1.5, label="Perfect prediction")
        ax.set_xlabel(f"Truth model  [{unit}]", fontsize=11)
        ax.set_ylabel(f"Surrogate prediction  [{unit}]", fontsize=11)
        ax.set_title(f"{label}   R²={r2_val:.4f}   RMSE={rmse:.4f} {unit}",
                     fontsize=10)
        ax.legend(fontsize=9)
        ax.grid(True, alpha=0.25)

    plt.tight_layout()
    plt.savefig("surrogate_validation.png", dpi=150, bbox_inches="tight")
    print("  Saved → surrogate_validation.png")
    plt.show()


# ============================================================
# 5)  SPLINE FITTING THROUGH OPTIMAL CONTROL POINTS
# ============================================================
#
# The optimizer outputs h_opt → a set of Bezier control points (P1..P5,
# D1..D4, B1..B4, FK, FW). These define the hull shape discretely.
#
# We now fit smooth parametric B-splines THROUGH those control points.
# This is the "line fitting" step: we go from a set of optimizer-chosen
# points to a continuous smooth curve that defines each hull feature.
#
# Why do this on top of Bezier curves?
#   The Bezier curves use fixed topology (4-5 control points per curve).
#   A B-spline fit gives us a smooth interpolating curve that passes
#   exactly through the optimizer's control points — this is the formal
#   definition of the optimal hull geometry as a continuous function,
#   independent of the Bezier parameterization.
#
# We fit three curves:
#   1. Keel profile   — spline through P1..P5  (side view, x-z plane)
#   2. Deck edge      — spline through D1..D4  (plan view, x-y plane)
#   3. Keel planform  — spline through B1..B4  (bottom view, x-y plane)
#
# We also fit a cubic spline to the cross-sectional half-beam and draft
# as functions of x — this gives a smooth, exportable hull offset table.
#

def fit_splines_to_control_points(h_opt: np.ndarray) -> dict:
    """
    Fit parametric B-splines through the optimal Bezier control points.

    Returns a dict of spline objects and evaluated curves for plotting
    and export.
    """
    cp  = build_control_points(h_opt, **CONST)
    cv  = hull_curves(cp, n=500)
    L   = CONST["L"]

    results = {}

    # ── 1. Keel profile spline (x-z plane) ───────────────────────────────────
    # Control points: P1, P2, P3, P4, P5
    keel_pts = np.array([cp["P1"], cp["P2"], cp["P3"], cp["P4"], cp["P5"]])
    kx, kz   = keel_pts[:, 0], keel_pts[:, 2]
    # Parametric B-spline interpolating through all 5 keel control points
    tck_keel, _ = splprep([kx, kz], s=0, k=min(3, len(kx)-1))
    u_fine      = np.linspace(0, 1, 300)
    kx_fit, kz_fit = splev(u_fine, tck_keel)
    results["keel_spline_pts"] = keel_pts
    results["keel_spline_curve"] = np.column_stack([kx_fit, kz_fit])
    results["tck_keel"] = tck_keel

    # ── 2. Deck edge spline (x-y plane, top view) ────────────────────────────
    # Control points: D1, D2, D3, D4
    deck_pts = np.array([cp["D1"], cp["D2"], cp["D3"], cp["D4"]])
    dx, dy   = deck_pts[:, 0], deck_pts[:, 1]
    tck_deck, _ = splprep([dx, dy], s=0, k=min(3, len(dx)-1))
    dx_fit, dy_fit = splev(u_fine, tck_deck)
    results["deck_spline_pts"] = deck_pts
    results["deck_spline_curve"] = np.column_stack([dx_fit, dy_fit])
    results["tck_deck"] = tck_deck

    # ── 3. Keel planform spline (x-y plane, bottom view) ─────────────────────
    # Control points: B1, B2, B3, B4
    bot_pts  = np.array([cp["B1"], cp["B2"], cp["B3"], cp["B4"]])
    bx, by   = bot_pts[:, 0], bot_pts[:, 1]
    tck_bot, _ = splprep([bx, by], s=0, k=min(3, len(bx)-1))
    bx_fit, by_fit = splev(u_fine, tck_bot)
    results["bot_spline_pts"]   = bot_pts
    results["bot_spline_curve"] = np.column_stack([bx_fit, by_fit])
    results["tck_bot"] = tck_bot

    # ── 4. Hull offset table: half-beam B(x) and draft T(x) ──────────────────
    # Sample the actual hull geometry at many stations, then fit cubic splines.
    # This is the most useful output for a naval architect — it's the offset
    # table that completely defines the hull form.
    xs_stations = np.linspace(0.02 * L, 0.98 * L, 60)
    y_hw = _sort_interp(cv["deck_edge"], xs_stations, col=1)   # half-beam
    z_k  = _sort_interp(cv["keel_line"], xs_stations, col=2)   # keel z
    draft_stations = np.maximum(-z_k, 0.0)

    # Cubic spline fits — smooth interpolation of the offset table
    cs_beam  = CubicSpline(xs_stations, y_hw,           bc_type="natural")
    cs_draft = CubicSpline(xs_stations, draft_stations,  bc_type="natural")

    xs_fine  = np.linspace(0.02 * L, 0.98 * L, 500)
    results["offset_xs"]       = xs_stations
    results["offset_beam"]     = y_hw
    results["offset_draft"]    = draft_stations
    results["cs_beam"]         = cs_beam
    results["cs_draft"]        = cs_draft
    results["beam_fit_curve"]  = np.column_stack([xs_fine, cs_beam(xs_fine)])
    results["draft_fit_curve"] = np.column_stack([xs_fine, cs_draft(xs_fine)])

    return results


def export_offset_table(
    spline_results: dict,
    path: str = "hull_offset_table.csv",
    n_export: int = 50,
) -> None:
    """
    Export the smooth hull offset table to CSV.

    Columns: x [m], half_beam [m], draft [m], section_area [m²]

    This is the primary geometry deliverable — it fully defines the
    hull form as a function of longitudinal position.
    """
    L       = CONST["L"]
    xs      = np.linspace(0.02 * L, 0.98 * L, n_export)
    beam    = spline_results["cs_beam"](xs)
    draft   = spline_results["cs_draft"](xs)
    sec_area = 0.5 * np.pi * beam * draft  # elliptic section area

    import csv
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["x_m", "half_beam_m", "draft_m", "section_area_m2"])
        for i in range(n_export):
            w.writerow([f"{xs[i]:.4f}", f"{beam[i]:.5f}",
                        f"{draft[i]:.5f}", f"{sec_area[i]:.5f}"])
    print(f"  Exported offset table → {path}  ({n_export} stations)")


def plot_spline_fits(
    h_opt:  np.ndarray,
    h_init: np.ndarray,
    spline_results: dict,
) -> None:
    """
    Four-panel plot showing:
      (A) Keel profile spline  vs  Bezier curve  vs  initial
      (B) Deck edge spline     vs  Bezier curve  vs  initial
      (C) Keel planform spline vs  Bezier curve  vs  initial
      (D) Hull offset table    — smooth beam(x) and draft(x) curves
    """
    cp_opt  = build_control_points(h_opt,  **CONST)
    cp_ini  = build_control_points(h_init, **CONST)
    cv_opt  = hull_curves(cp_opt,  n=500)
    cv_ini  = hull_curves(cp_ini,  n=500)
    L = CONST["L"]

    BLUE   = "steelblue"
    ORANGE = "darkorange"
    GREEN  = "seagreen"

    fig = plt.figure(figsize=(16, 12))
    fig.suptitle(
        "Optimal Hull — B-Spline Fits Through Optimizer Control Points\n"
        "Goal: continuous smooth hull geometry from discrete optimizer output",
        fontsize=13, fontweight="bold",
    )
    gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.42, wspace=0.32)

    # ── (A) Keel profile: x-z plane ──────────────────────────────────────────
    ax = fig.add_subplot(gs[0, 0])
    # Initial Bezier
    kl_ini = cv_ini["keel_line"]
    ax.plot(kl_ini[:, 0], kl_ini[:, 2], color=BLUE, lw=1.8, ls="--",
            label="Initial (Bezier)", alpha=0.7)
    # Optimal Bezier
    kl_opt = cv_opt["keel_line"]
    ax.plot(kl_opt[:, 0], kl_opt[:, 2], color=ORANGE, lw=1.8, ls="--",
            label="Optimal (Bezier)", alpha=0.7)
    # Spline fit through optimal control points
    sk = spline_results["keel_spline_curve"]
    ax.plot(sk[:, 0], sk[:, 1], color=GREEN, lw=2.5,
            label="Optimal (B-spline fit)")
    # Control points
    kpts = spline_results["keel_spline_pts"]
    ax.scatter(kpts[:, 0], kpts[:, 2], s=80, color=GREEN, zorder=6,
               edgecolors="white", lw=0.8, label="Control points (P1..P5)")
    for j, name in enumerate(["P1","P2","P3","P4","P5"]):
        ax.annotate(name, (kpts[j, 0], kpts[j, 2]),
                    textcoords="offset points", xytext=(5, 4),
                    fontsize=7, color=GREEN, fontweight="bold")
    ax.axhline(0, color="navy", lw=0.8, ls=":", alpha=0.6, label="Waterline")
    ax.set_xlabel("x  [m]", fontsize=10);  ax.set_ylabel("z  [m]", fontsize=10)
    ax.set_title("(A) Keel Profile  (x-z plane)", fontsize=10)
    ax.legend(fontsize=7, loc="lower right");  ax.grid(True, alpha=0.25)

    # ── (B) Deck edge: x-y plan view ─────────────────────────────────────────
    ax2 = fig.add_subplot(gs[0, 1])
    de_ini = cv_ini["deck_edge"]
    ax2.plot(de_ini[:, 0], de_ini[:, 1], color=BLUE, lw=1.8, ls="--",
             label="Initial (Bezier)", alpha=0.7)
    de_opt = cv_opt["deck_edge"]
    ax2.plot(de_opt[:, 0], de_opt[:, 1], color=ORANGE, lw=1.8, ls="--",
             label="Optimal (Bezier)", alpha=0.7)
    sd = spline_results["deck_spline_curve"]
    ax2.plot(sd[:, 0], sd[:, 1], color=GREEN, lw=2.5,
             label="Optimal (B-spline fit)")
    dpts = spline_results["deck_spline_pts"]
    ax2.scatter(dpts[:, 0], dpts[:, 1], s=80, color=GREEN, zorder=6,
                edgecolors="white", lw=0.8, label="Control points (D1..D4)")
    for j, name in enumerate(["D1","D2","D3","D4"]):
        ax2.annotate(name, (dpts[j, 0], dpts[j, 1]),
                     textcoords="offset points", xytext=(5, 4),
                     fontsize=7, color=GREEN, fontweight="bold")
    ax2.set_xlabel("x  [m]", fontsize=10);  ax2.set_ylabel("y  [m]", fontsize=10)
    ax2.set_title("(B) Deck Edge Plan  (x-y plane)", fontsize=10)
    ax2.legend(fontsize=7);  ax2.grid(True, alpha=0.25)

    # ── (C) Keel planform: x-y bottom view ───────────────────────────────────
    ax3 = fig.add_subplot(gs[1, 0])
    kp_ini = cv_ini["keel_plan"]
    ax3.plot(kp_ini[:, 0],  kp_ini[:, 1], color=BLUE, lw=1.8, ls="--", alpha=0.7)
    ax3.plot(kp_ini[:, 0], -kp_ini[:, 1], color=BLUE, lw=1.8, ls="--",
             label="Initial (Bezier)", alpha=0.7)
    kp_opt = cv_opt["keel_plan"]
    ax3.plot(kp_opt[:, 0],  kp_opt[:, 1], color=ORANGE, lw=1.8, ls="--", alpha=0.7)
    ax3.plot(kp_opt[:, 0], -kp_opt[:, 1], color=ORANGE, lw=1.8, ls="--",
             label="Optimal (Bezier)", alpha=0.7)
    sb = spline_results["bot_spline_curve"]
    ax3.plot(sb[:, 0],  sb[:, 1], color=GREEN, lw=2.5, label="Optimal (B-spline fit)")
    ax3.plot(sb[:, 0], -sb[:, 1], color=GREEN, lw=2.5)
    bpts = spline_results["bot_spline_pts"]
    ax3.scatter(bpts[:, 0],  bpts[:, 1], s=80, color=GREEN, zorder=6,
                edgecolors="white", lw=0.8, label="Control points (B1..B4)")
    ax3.scatter(bpts[:, 0], -bpts[:, 1], s=80, color=GREEN, zorder=6,
                edgecolors="white", lw=0.8)
    for j, name in enumerate(["B1","B2","B3","B4"]):
        ax3.annotate(name, (bpts[j, 0], bpts[j, 1]),
                     textcoords="offset points", xytext=(4, 4),
                     fontsize=7, color=GREEN, fontweight="bold")
    ax3.axhline(0, color="gray", lw=0.6, ls="--", alpha=0.4)
    ax3.set_xlabel("x  [m]", fontsize=10);  ax3.set_ylabel("y  [m]", fontsize=10)
    ax3.set_title("(C) Keel Planform  (x-y bottom view)", fontsize=10)
    ax3.legend(fontsize=7);  ax3.grid(True, alpha=0.25)

    # ── (D) Hull offset table: beam(x) and draft(x) ──────────────────────────
    ax4 = fig.add_subplot(gs[1, 1])

    # Sampled truth values from the Bezier geometry
    xs_s   = spline_results["offset_xs"]
    beam_s = spline_results["offset_beam"]
    draft_s= spline_results["offset_draft"]
    ax4.scatter(xs_s, beam_s,  s=18, color=ORANGE, alpha=0.8, label="Beam sample pts")
    ax4.scatter(xs_s, draft_s, s=18, color=BLUE,   alpha=0.8, label="Draft sample pts",
                marker="s")

    # Cubic spline fits
    bf = spline_results["beam_fit_curve"]
    df = spline_results["draft_fit_curve"]
    ax4.plot(bf[:, 0], bf[:, 1], color=GREEN, lw=2.2, label="Beam B(x)  [cubic spline]")
    ax4.plot(df[:, 0], df[:, 1], color="purple", lw=2.2,
             label="Draft T(x)  [cubic spline]")

    # Initial hull comparison
    L_val = CONST["L"]
    xs_ini = np.linspace(0.02*L_val, 0.98*L_val, 80)
    cp_i2  = build_control_points(h_init, **CONST)
    cv_i2  = hull_curves(cp_i2, n=500)
    beam_ini  = _sort_interp(cv_i2["deck_edge"], xs_ini, col=1)
    draft_ini = np.maximum(-_sort_interp(cv_i2["keel_line"], xs_ini, col=2), 0.0)
    ax4.plot(xs_ini, beam_ini,  color=BLUE,   lw=1.2, ls=":", alpha=0.6,
             label="Initial beam")
    ax4.plot(xs_ini, draft_ini, color="navy", lw=1.2, ls=":", alpha=0.6,
             label="Initial draft")

    ax4.set_xlabel("x  [m]  (station)", fontsize=10)
    ax4.set_ylabel("dimension  [m]",    fontsize=10)
    ax4.set_title("(D) Hull Offset Table — B(x) and T(x)\n"
                  "[cubic spline through sampled geometry]", fontsize=10)
    ax4.legend(fontsize=7, loc="upper right");  ax4.grid(True, alpha=0.25)
    ax4.set_xlim(0, L_val)

    plt.savefig("hull_spline_fits.png", dpi=150, bbox_inches="tight")
    print("  Saved → hull_spline_fits.png")
    plt.show()


# ============================================================
# 8)  PAPER-STYLE 3-VIEW HULL GEOMETRY PLOT
# ============================================================
#
# Reproduces the figure layout from the research paper:
#
#   (a) PROFILE VIEW  (x-z plane, side view)
#       Shows: keel Bezier P1→P2→P3→P4→P5→P6, deck line,
#              chine curve C1→C2→C3→C4→C5, all control points labelled
#
#   (b) DECK VIEW  (x-y plane, top-down)
#       Shows: deck edge D1→D2→D3→D4, chine C1→C2→C3→C4→C5,
#              keel planform B1→B2→B3→B4, all control points labelled
#
#   (c) FRONT VIEW  (y-z plane, bow-on cross-section)
#       Shows: bow cross-section Bezier with FK (keel depth) and FW (hull width)
#
# Control point naming matches the paper diagram as closely as possible
# given our parameterisation (P1..P5, C1..C5, D1..D4, B1..B4, FK, FW).
#

def plot_paper_style_views(
    h_opt:  np.ndarray,
    h_init: np.ndarray,
    R_init: float,
    V_init: float,
    R_opt:  float,
    V_opt:  float,
) -> None:
    """
    Paper-style three-view drawing of the optimal hull with labelled
    control points, matching the layout from the research paper image.

    Shows initial hull (blue dashed) and optimal hull (orange solid)
    overlaid on all three views.
    """
    cp_i = build_control_points(h_init, **CONST)
    cp_o = build_control_points(h_opt,  **CONST)
    cv_i = hull_curves(cp_i, n=400)
    cv_o = hull_curves(cp_o, n=400)

    L, B, T, F = CONST["L"], CONST["B"], CONST["T"], CONST["F"]

    BLUE   = "steelblue"
    ORANGE = "darkorange"
    RED    = "#c0392b"
    GREEN  = "#27ae60"
    GOLD   = "#d4ac0d"
    PURPLE = "#8e44ad"

    fig = plt.figure(figsize=(18, 14))
    fig.patch.set_facecolor("white")
    fig.suptitle(
        f"Optimal Hull Geometry — Three-View Drawing\n"
        f"Initial:  R = {R_init:.3f} N,  V = {V_init:.4f} m³     "
        f"Optimal:  R = {R_opt:.3f} N  ({100*(R_init-R_opt)/R_init:.1f}% reduction),  "
        f"V = {V_opt:.4f} m³",
        fontsize=13, fontweight="bold", y=0.98,
    )

    gs = gridspec.GridSpec(
        2, 2,
        figure=fig,
        height_ratios=[1.1, 1.0],
        hspace=0.38, wspace=0.28,
    )

    # =========================================================================
    # (a) PROFILE VIEW  —  x-z plane  (top row, full width)
    # =========================================================================
    ax_prof = fig.add_subplot(gs[0, :])

    for cv, cp, color, lw, ls, alpha, tag in [
        (cv_i, cp_i, BLUE,   1.6, "--", 0.65, "Initial"),
        (cv_o, cp_o, ORANGE, 2.5, "-",  1.00, "Optimal"),
    ]:
        keel = cv["keel_line"]
        deck = cv["deck_line"]

        # Deck (flat line at z=F)
        ax_prof.plot(deck[:, 0], deck[:, 2],
                     color=color, lw=lw, ls=ls, alpha=alpha,
                     label=f"{tag}  R={compute_R_and_V(h_opt if tag=='Optimal' else h_init, **CONST)[0]:.3f} N")

        # Keel Bezier
        ax_prof.plot(keel[:, 0], keel[:, 2],
                     color=color, lw=lw, ls=ls, alpha=alpha)

        # Bow vertical from deck to P2
        ax_prof.plot([0, 0], [F, cp["P2"][2]],
                     color=color, lw=max(lw-0.6, 0.8), ls=":", alpha=alpha)

        # Fill hull cross-section
        xq  = np.linspace(0, L, 400)
        idx = np.argsort(keel[:, 0])
        zk  = np.interp(xq, keel[idx, 0], keel[idx, 2])
        ax_prof.fill_between(xq, np.full_like(xq, F), zk,
                             alpha=0.10 if tag == "Initial" else 0.18,
                             color=color)

    # Label optimal control points only (paper style: dots + labels)
    keel_pts_opt = np.array([
        cp_o["P1"], cp_o["P2"], cp_o["P3"], cp_o["P4"], cp_o["P5"]
    ])
    pt_names = ["P₁(0,0,F)", "P₂(0,0,h₁)", "P₃(h₂,0,T)", "P₄(h₃,0,T)", "P₅(L,0,F)"]
    pt_colors = [RED, RED, RED, RED, RED]
    offsets   = [(6, 5), (6, -14), (4, 6), (4, 6), (-50, 5)]

    for pt, name, col, off in zip(keel_pts_opt, pt_names, pt_colors, offsets):
        ax_prof.scatter(pt[0], pt[2], s=60, color=col, zorder=8,
                        edgecolors="white", linewidths=0.7)
        ax_prof.annotate(name, (pt[0], pt[2]),
                         textcoords="offset points", xytext=off,
                         fontsize=8, color=col, fontweight="bold",
                         bbox=dict(boxstyle="round,pad=0.15", fc="white",
                                   ec="none", alpha=0.7))

    # Waterline
    ax_prof.axhline(0, color="navy", lw=1.0, ls=":", alpha=0.7, label="Waterline (z=0)")

    # Annotations: dimension arrows
    ax_prof.annotate("", xy=(L, -T - 0.03), xytext=(0, -T - 0.03),
                     arrowprops=dict(arrowstyle="<->", color="gray", lw=1.0))
    ax_prof.text(L/2, -T - 0.055, f"L = {L:.2f} m", ha="center", va="top",
                 fontsize=8, color="gray")
    ax_prof.annotate("", xy=(-0.06, F), xytext=(-0.06, -T),
                     arrowprops=dict(arrowstyle="<->", color="gray", lw=1.0))
    ax_prof.text(-0.085, (F - T)/2, f"F+T\n={F+T:.2f}m", ha="center", va="center",
                 fontsize=7, color="gray")

    ax_prof.set_xlabel("x  [m]  — Length", fontsize=11)
    ax_prof.set_ylabel("z  [m]  — Height", fontsize=11)
    ax_prof.set_title("(a) Profile View  —  x-z plane\n"
                      "[Bezier keel:  P₁→P₂→P₃→P₄→P₅,  flat deck at z = F]",
                      fontsize=10)
    ax_prof.legend(fontsize=8, loc="upper right")
    ax_prof.set_xlim(-0.10, L + 0.05)
    ax_prof.set_ylim(-T - 0.09, F + 0.08)
    ax_prof.set_aspect("equal")
    ax_prof.grid(True, alpha=0.20)

    # =========================================================================
    # (b) DECK VIEW  —  x-y plane  (bottom-left)
    # =========================================================================
    ax_deck = fig.add_subplot(gs[1, 0])

    for cv, cp, color, lw, ls, alpha, tag in [
        (cv_i, cp_i, BLUE,   1.6, "--", 0.65, "Initial"),
        (cv_o, cp_o, ORANGE, 2.5, "-",  1.00, "Optimal"),
    ]:
        de = cv["deck_edge"]
        kp = cv["keel_plan"]

        # Deck edge (starboard) and its mirror (port)
        ax_deck.plot(de[:, 0],  de[:, 1], color=color, lw=lw, ls=ls, alpha=alpha,
                     label=f"{tag}" if tag == "Initial" else f"{tag} (optimal)")
        ax_deck.plot(de[:, 0], -de[:, 1], color=color, lw=lw, ls=ls, alpha=alpha)

        # Keel planform (starboard + port)
        ax_deck.plot(kp[:, 0],  kp[:, 1], color=color, lw=max(lw-0.5, 1.0),
                     ls=ls, alpha=alpha * 0.8)
        ax_deck.plot(kp[:, 0], -kp[:, 1], color=color, lw=max(lw-0.5, 1.0),
                     ls=ls, alpha=alpha * 0.8)

        # Fill hull footprint
        ax_deck.fill_between(de[:, 0],  de[:, 1], -de[:, 1],
                             alpha=0.08 if tag == "Initial" else 0.15,
                             color=color)

    # Label deck edge control points on optimal hull
    deck_pts = [cp_o["D1"], cp_o["D2"], cp_o["D3"], cp_o["D4"]]
    d_names  = ["D₁(0,B,F)", "D₂(h₆,h₇,F)", "D₃(h₈,h₉,F)", "D₄(h₁₀,h₁₁,F)"]
    d_off    = [(-5, 8), (4, 8), (4, 8), (4, -14)]
    for pt, name, off in zip(deck_pts, d_names, d_off):
        ax_deck.scatter(pt[0],  pt[1], s=55, color=GREEN, zorder=8,
                        edgecolors="white", linewidths=0.7)
        ax_deck.scatter(pt[0], -pt[1], s=55, color=GREEN, zorder=8,
                        edgecolors="white", linewidths=0.7)
        ax_deck.annotate(name, (pt[0], pt[1]),
                         textcoords="offset points", xytext=off,
                         fontsize=7, color=GREEN, fontweight="bold",
                         bbox=dict(boxstyle="round,pad=0.1", fc="white",
                                   ec="none", alpha=0.7))

    # Label keel planform control points
    bot_pts = [cp_o["B1"], cp_o["B2"], cp_o["B3"], cp_o["B4"]]
    b_names = ["B₁(h₂₄,0,T)", "B₂(h₂₅,h₂₆,T)", "B₃(h₂₇,h₂₈,T)", "B₄(h₂₉,0,T)"]
    b_off   = [(2, -14), (4, -14), (4, -14), (-55, -14)]
    for pt, name, off in zip(bot_pts, b_names, b_off):
        ax_deck.scatter(pt[0],  pt[1], s=55, color=GOLD, zorder=8,
                        edgecolors="white", linewidths=0.7)
        ax_deck.scatter(pt[0], -pt[1], s=55, color=GOLD, zorder=8,
                        edgecolors="white", linewidths=0.7)
        ax_deck.annotate(name, (pt[0], pt[1]),
                         textcoords="offset points", xytext=off,
                         fontsize=7, color=GOLD, fontweight="bold",
                         bbox=dict(boxstyle="round,pad=0.1", fc="white",
                                   ec="none", alpha=0.7))

    ax_deck.axhline(0, color="gray", lw=0.7, ls="--", alpha=0.5, label="Centreline")
    ax_deck.set_xlabel("x  [m]  — Length", fontsize=10)
    ax_deck.set_ylabel("y  [m]  — Half-beam", fontsize=10)
    ax_deck.set_title("(b) Deck / Plan View  —  x-y plane\n"
                      "[Green = deck edge D₁..D₄,  Gold = keel plan B₁..B₄]",
                      fontsize=10)
    ax_deck.legend(fontsize=7, loc="upper right")
    ax_deck.set_xlim(-0.03, L + 0.03)
    ax_deck.set_aspect("equal")
    ax_deck.grid(True, alpha=0.20)

    # =========================================================================
    # (c) FRONT VIEW  —  y-z plane  (bottom-right)
    # =========================================================================
    ax_front = fig.add_subplot(gs[1, 1])

    stations = [
        (0.05 * L, "-",  1.0, "Bow  (x=0.05L)"),
        (0.50 * L, "--", 0.8, "Mid  (x=0.50L)"),
        (0.90 * L, ":",  0.7, "Aft  (x=0.90L)"),
    ]

    for cv, cp, color, base_lw, base_alpha in [
        (cv_i, cp_i, BLUE,   1.4, 0.60),
        (cv_o, cp_o, ORANGE, 2.2, 1.00),
    ]:
        for x_st, ls, alpha_fac, st_label in stations:
            y_cs, z_cs = cross_section_ellipse(x_st, cv)
            hb = float(_sort_interp(cv["deck_edge"], np.array([x_st]), col=1))
            lbl = (f"{'Initial' if color==BLUE else 'Optimal'}  {st_label}"
                   if color == ORANGE else None)
            ax_front.plot(y_cs, z_cs, color=color, lw=base_lw,
                          ls=ls, alpha=base_alpha * alpha_fac, label=lbl)
            ax_front.plot([-hb, hb], [0, 0],
                          color=color, lw=0.7, ls=ls,
                          alpha=base_alpha * alpha_fac * 0.5)
            if color == ORANGE:
                ax_front.fill_between(y_cs, z_cs, 0, alpha=0.06, color=color)

        # Bow Bezier cross-section (most detailed)
        y_bow, z_bow = cross_section_bezier(cv)
        ax_front.plot(y_bow, z_bow, color=color, lw=base_lw + 0.5,
                      ls="-", alpha=base_alpha, zorder=5)

        # FK and FW control points (optimal only)
        if color == ORANGE:
            FK, FW = cp["FK"], cp["FW"]
            ax_front.scatter(FK[1], FK[2], s=100, color=PURPLE,
                             zorder=9, edgecolors="white", linewidths=0.8,
                             marker="^", label="FK  keel depth")
            ax_front.annotate(
                f"FK(0,0,−h₁₆·T)\n= (0,0,{FK[2]:.3f})",
                (FK[1], FK[2]),
                textcoords="offset points", xytext=(8, -18),
                fontsize=7, color=PURPLE, fontweight="bold",
                bbox=dict(boxstyle="round,pad=0.15", fc="white",
                          ec="none", alpha=0.8),
            )
            for sign, side in [(+1, "stbd"), (-1, "port")]:
                ax_front.scatter(sign * FW[1], FW[2], s=100, color=PURPLE,
                                 zorder=9, edgecolors="white", linewidths=0.8,
                                 marker="s")
            ax_front.annotate(
                f"FW(0,h₁₇·B,0)\n= (0,±{FW[1]:.3f},0)",
                (FW[1], FW[2]),
                textcoords="offset points", xytext=(6, 6),
                fontsize=7, color=PURPLE, fontweight="bold",
                bbox=dict(boxstyle="round,pad=0.15", fc="white",
                          ec="none", alpha=0.8),
            )

    ax_front.axhline(0, color="navy", lw=1.0, ls=":", alpha=0.7, label="Waterline")
    ax_front.axvline(0, color="gray",  lw=0.6, ls="--", alpha=0.4, label="Centreline")

    ax_front.set_xlabel("y  [m]  — Half-beam", fontsize=10)
    ax_front.set_ylabel("z  [m]  — Height",    fontsize=10)
    ax_front.set_title("(c) Front / Bow-On View  —  y-z plane\n"
                       "[solid=bow Bezier,  dashed=mid station,  dotted=aft station]",
                       fontsize=10)
    ax_front.set_aspect("equal")
    ax_front.grid(True, alpha=0.20)
    ax_front.legend(handles=[
        Line2D([], [], color=BLUE,   lw=2, ls="--", label="Initial hull"),
        Line2D([], [], color=ORANGE, lw=2.5,        label="Optimal hull"),
        Line2D([], [], color="k",    lw=2.0, ls="-",  label="Bow station"),
        Line2D([], [], color="k",    lw=1.5, ls="--", label="Mid station"),
        Line2D([], [], color="k",    lw=1.5, ls=":",  label="Aft station"),
        Line2D([], [], color=PURPLE, lw=0, marker="^", markersize=7,
               label="FK  keel depth"),
        Line2D([], [], color=PURPLE, lw=0, marker="s", markersize=7,
               label="FW  hull width"),
    ], fontsize=7, loc="lower center", ncol=2)

    plt.savefig("hull_three_view.png", dpi=160, bbox_inches="tight",
                facecolor="white")
    print("  Saved → hull_three_view.png")
    plt.show()


# ============================================================
# 9)  MAIN
# ============================================================

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Hull MDO surrogate pipeline")
    parser.add_argument("--csv",   type=str,   default="hull_dataset.csv",
                        help="Path to dataset CSV  (default: hull_dataset.csv)")
    parser.add_argument("--gamma", type=float, default=0.02,
                        help="Volume constraint band ±γ  (default: 0.02 = ±2%%)")
    parser.add_argument("--lam",   type=float, default=1e-4,
                        help="RBF regularisation λ  (default: 1e-4)")
    args = parser.parse_args()

    SEP = "=" * 60

    # ── Step 1: Load dataset ──────────────────────────────────────────────────
    print(SEP)
    print("STEP 1 — Load dataset")
    print(SEP)
    H, R, V = load_csv(args.csv)

    # ── Step 2: Train / test split (50 / 50) ─────────────────────────────────
    print(f"\n{SEP}")
    print("STEP 2 — Train / test split  (50% / 50%)")
    print(SEP)
    H_tr, R_tr, V_tr, H_te, R_te, V_te = train_test_split(H, R, V,
                                                            test_fraction=0.5)
    print(f"  Train: {len(R_tr)} samples   Test: {len(R_te)} samples")

    # ── Step 3: Fit surrogates on train half ──────────────────────────────────
    print(f"\n{SEP}")
    print("STEP 3 — Fit RBF surrogates on TRAIN half  (h → R,  h → V)")
    print(SEP)
    R_surr = fit_rbf(H_tr, R_tr, lam=args.lam)
    V_surr = fit_rbf(H_tr, V_tr, lam=args.lam)

    R_train_pred = predict_rbf_numpy(H_tr, R_surr)
    V_train_pred = predict_rbf_numpy(H_tr, V_surr)
    rmse = lambda a, b: float(np.sqrt(np.mean((a - b)**2)))
    print(f"  Train RMSE   R: {rmse(R_tr, R_train_pred):.4f} N   "
          f"V: {rmse(V_tr, V_train_pred):.5f} m³")

    # ── Step 4: Validate on test half ─────────────────────────────────────────
    print(f"\n{SEP}")
    print("STEP 4 — Validate on TEST half  (compare surrogate vs truth model)")
    print(SEP)
    metrics = validate_surrogate(H_te, R_te, V_te, R_surr, V_surr)
    print_validation(metrics, n_train=len(R_tr), n_test=len(R_te))
    plot_validation(R_te, V_te, metrics)

    # ── Step 5: Optimise ──────────────────────────────────────────────────────
    print(f"\n{SEP}")
    print("STEP 5 — CSDL + SQP optimisation")
    print(SEP)
    h0    = 0.5 * np.ones(29)
    _, V_ref = compute_R_and_V(h0, **CONST)
    gamma = args.gamma
    print(f"  Starting point: h = 0.5 everywhere")
    print(f"  V_ref  = {V_ref:.5f} m³")
    print(f"  γ      = {gamma}  →  volume band "
          f"[{(1-gamma)*V_ref:.5f}, {(1+gamma)*V_ref:.5f}] m³")

    prob, sim = build_problem(R_surr, V_surr,
                               V_ref, gamma=gamma, h0=h0.copy())
    solver = opt.SQP(prob, maxiter=300, opt_tol=1e-8, recording=True)
    solver.solve()
    h_opt = solver.results["x"]

    # ── Step 6: Truth-model evaluation of optimal design ─────────────────────
    print(f"\n{SEP}")
    print("STEP 6 — Results evaluated on TRUTH model")
    print(SEP)
    Ri, Vi = compute_R_and_V(h0,    **CONST)
    Ro, Vo = compute_R_and_V(h_opt, **CONST)
    Rs_opt = float(predict_rbf_numpy(h_opt, R_surr))
    Vs_opt = float(predict_rbf_numpy(h_opt, V_surr))

    print(f"  Initial design:")
    print(f"    R = {Ri:.4f} N    V = {Vi:.5f} m³")
    print(f"  Optimal design:")
    print(f"    R = {Ro:.4f} N  ({100*(Ri-Ro)/Ri:.1f}% reduction)  "
          f"[surrogate predicted {Rs_opt:.4f} N]")
    print(f"    V = {Vo:.5f} m³  (band: ±{gamma*100:.0f}% of {V_ref:.5f})  "
          f"[surrogate predicted {Vs_opt:.5f} m³]")
    in_band = (1-gamma)*V_ref <= Vo <= (1+gamma)*V_ref
    print(f"    Volume constraint: {'✓ satisfied' if in_band else '✗ VIOLATED'}")

    # ── Step 7: Paper-style three-view drawing ───────────────────────────────
    print(f"\n{SEP}")
    print("STEP 7 — Paper-style three-view hull drawing")
    print(SEP)
    plot_paper_style_views(h_opt, h0, Ri, Vi, Ro, Vo)

    # ── Step 8: Spline fitting through optimizer control points ───────────────
    print(f"\n{SEP}")
    print("STEP 8 — B-spline fitting through optimal control points")
    print(SEP)
    print("  Fitting B-splines to keel profile, deck edge, keel planform...")
    spline_res = fit_splines_to_control_points(h_opt)
    plot_spline_fits(h_opt, h0, spline_res)
    export_offset_table(spline_res, path="hull_offset_table.csv")

    print(f"\n{'='*60}")
    print("Pipeline complete. Output files:")
    print("  surrogate_validation.png  — test set parity plots")
    print("  hull_three_view.png       — paper-style 3-view drawing")
    print("  hull_spline_fits.png      — B-spline fits through control pts")
    print("  hull_offset_table.csv     — offset table B(x), T(x)")
    print("="*60)